### ISSUE TITLE
Error when accessing settings

### ISSUE THREAD

**Issue by gjackson12** [OpenDevelopmentMekong/wpckan#341]
I receive the following error when trying to access settings: 
`
Fatal error: Uncaught ArgumentCountError: Too few arguments to function do_settings_fields(), 1 passed in /var/www/html/wp-content/plugins/wpckan/templates/settings.php on line 5 and exactly 2 expected in /var/www/html/wp-admin/includes/template.php:1356 Stack trace: #0 /var/www/html/wp-content/plugins/wpckan/templates/settings.php(5): do_settings_fields('wpckan-group') #1 /var/www/html/wp-content/plugins/wpckan/wpckan.php(208): include('/var/www/html/w...') #2 /var/www/html/wp-includes/class-wp-hook.php(286): wpckan->plugin_settings_page('') #3 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /var/www/html/wp-admin/admin.php(224): do_action('settings_page_w...') #6 /var/www/html/wp-admin/options-general.php(10): require_once('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-admin/includes/template.php on line 1356`

**Comment by chrisweight** [comment]
FWIW, I patched this locally by supplying a second argument to the method:
```
 <?php @do_settings_fields('wpckan-group', 'wpckan-section'); ?>
```
in `settings.php`
